POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Anna",
    "number": "040-1234556"
}

###

PUT http://localhost:3001/api/persons/64f5ca3bd8eadbe9fe241aa5
content-type: application/json

{
    "name": "Lora",
    "number": 040-1234556
}


