GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxvcmE1IiwiaWQiOiI2NGZhYmE4MmJmYWU5ZjgzY2IzMTE0YjAiLCJpYXQiOjE2OTQxNTQ1NzV9.yKIobQOEqcqkK1qVY8a8o65KwVuFumMLdVJz01cOwvs

{
    "url": "https://test2.com",
    "title": "2e33test",
    "author": "2Tester Tester",
    "user": "Lora4"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "Lora5",
    "name": "Lora4 Lora4",
    "password": "123456"
}

###

GET http://localhost:3003/api/users
