GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "url": "https://test1.com",
    "title": "1test",
    "author": "1Tester Tester",
    "user": "Lera"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "Lera",
    "name": "Lera Lera",
    "password": "LALALALLA"
}

###

GET http://localhost:3003/api/users
