GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "url": "https://test2.com",
    "title": "2test",
    "author": "2Tester Tester",
    "user": "Lora4"
}

###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "Lora5",
    "name": "Lora4 Lora4",
    "password": "123456"
}

###

GET http://localhost:3003/api/users
